/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j10;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;

class AppTest {
    @Test void appHasAGreeting() throws IOException {
        J10 j10 = new J10();        
        assertEquals(13140, j10.p1(j10.lecture("src/test/resources/test.txt")));
    }
}
