/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j15;

import java.io.IOException;

public class App {
  

    public static void main(String[] args) throws IOException {
        J15 j15 = new J15("src/main/resources/j15.txt");
        Point[] co = new Point[2];
        co[0]= new Point(8,7);
        co[1]= new Point(2,10);
      //  j15.init();
       // j15.losange(co);
       System.out.println(j15.p1(2000000));
    }
}
//