/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j6;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    J6 j6 = new J6();

   

    @Test void testp12() {
        assertEquals(5, j6.p1("bvwbjplbgvbhsrlpgdmjqwftvncz"));
     }

     @Test void testp13() {
        assertEquals(6, j6.p1("nppdvjthqldpwncqszvftbrmjlhg"));
     }


    @Test void testp14() {
        assertEquals(10, j6.p1("nznrnfrfntjfmvfwmzdfjlvtqnbhcprsg"));
     }
     
     @Test void testp15() {
        assertEquals(11, j6.p1("zcfzfwzzqfrljwzlrfnpqdbhtmscgvjw"));
     }
}
