/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j9;

import java.io.IOException;

public class App {
   

    public static void main(String[] args) throws IOException {
        J9 j9 = new J9();
        j9.p2(j9.lecture("src/main/resources/j9.txt"));
    }
}
