/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j15;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;

class AppTest {
    @Test void testP1() throws IOException {
       J15 j15 = new J15("src/test/resources/test.txt");
        assertEquals(26, j15.p1(10));
    }
}
