/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j4;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;

class AppTest {
    J4 app;
    @Test
    void testOK1() throws IOException {
        app = new J4();
        assertEquals(2, app.j4P1("src/main/resources/test.txt")); 
       // app.
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    void testOK2() throws IOException {
        app = new J4();
        assertEquals(4, app.j4P2("src/main/resources/test.txt")); 
       // app.
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
