/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j1;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;

class AppTest {
    @Test
    void testp1() throws IOException {
        J1 j1 = new J1();
        assertEquals(24000, j1.p1("src/test/resources/test.txt"));
    }
    @Test
    void testp2() throws IOException {
        J1 j1 = new J1();
        assertEquals(45000, j1.p2("src/test/resources/test.txt"));
    }
}
