/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j3;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

public class App {

    public static int score(int[]t1 , int[]t2){
       int s = 0 ;
        // si t1[i] est dans t2 => s = s + t1
        for (int i = 0 ; i < t2.length ; i++){
            for (int j = 0 ; j <t2.length ; j++){
                if (t1[i] == t2[j]){
                    s=t1[i];
                }
            }
        }
        return s;
    }


public static void p1() throws IOException{
    String fileName = "src/main/resources/test.txt";
    File file = new File(fileName);
    FileReader fr = new FileReader(file);
    long scores = 0 ;
    
    try (BufferedReader br = new BufferedReader(fr)) {
        String line;
        while((line = br.readLine()) != null){
            int n = line.length();
            String gauche = line.substring(0, n/2);
            String droite = line.substring(n/2, n);
            //System.out.println(gauche + " - " + droite);

            // A -> Z : 65 -> 90 ;  aoc 27 - 52
            // a -> z : 97 -> 122; aoc 1 - 26
            // 

            int [] t1 = new int[n/2];
            int [] t2 = new int[n/2];

            for (int i = 0 ; i < n/2;i++){
                if(Character.isUpperCase( gauche.charAt(i))){
                    t1[i] =  (int)gauche.charAt(i) - 38 ;
                }
                if(Character.isLowerCase( gauche.charAt(i))){
                    t1[i] = (int)gauche.charAt(i)  - 96;
                }
                if(Character.isUpperCase( droite.charAt(i))){
                    t2[i ] = (int)droite.charAt(i) - 38;
                }
                if(Character.isLowerCase( droite.charAt(i))){
                    t2[i] = (int)droite.charAt(i) - 96 ;
                }
                //System.out.println(t1[i] );

            }

            System.out.println(scores);
           
        scores+=score(t1,t2);
         
        }
        System.out.println(scores);
    }
}

    public static void main(String[] args) throws IOException {
      p1();
    }
}
