/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j7;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    J7 j7 = new J7();
    @Test void testCD() {
      
        assertTrue(j7.isCdAvance("$ cd e"));
        assertTrue(j7.isCdRetour("$ cd .."));

    }

    @Test void isfile() {
      
        assertTrue(j7.isFile("62596 h.lst" ));
        assertFalse(j7.isFile("$ ls" ));

    }

    @Test void isDirectory() {
      
        assertTrue(j7.isDirectory("dir p" ));

    }


}
