/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j7;

import java.io.IOException;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException {
        J7 j7 = new J7();
        List<String> lines = j7.lecture("src/main/resources/j7.txt");
        j7.p1(lines);
    }
}
