/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j1;

import java.io.IOException;

public class App {
   
    

    public static void main(String[] args) throws IOException {
        J1 j1 = new J1();
        System.out.println(j1.p2("src/main/resources/j1.txt"));
    }
}
