/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j11;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;
import java.util.*;
class AppTest {}