/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j8;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.IOException;

class AppTest {
    @Test void appHasAGreeting() throws IOException {
        J8 j8 = new J8();
       assertEquals(21, j8.p1(j8.lecture("src/test/resources/test.txt")));
    }
}
