/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j2;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;

public class App {

    public static int[] conv(char c1 , char c2){
        int []t = new int[2];
        if (c1 == 'A' ){
            t[0] = 1;
        }
        if (c1 == 'B'){
            t[0] = 2;
        }
        if (c1 == 'C'){
            t[0] = 3;
        }
        if (c2 == 'X'){
            t[1] = 1;
        }
        if (c2 == 'Y'){
            t[1] = 2;
        }
        if (c2 == 'Z'){
            t[1] = 3;
        }
        return t;
    }

/* A B C == X Y Z == Rock Paper Scissors
 * 1 for Rock, 2 for Paper, and 3 for Scissors) 
 * plus the score for the outcome of the round :
    * 0 if you lost, 
    * 3 if the round was a draw,
    * and 6 if you won
 */
    public static void main(String[] args) throws IOException {
        String fileName = "src/main/resources/test0.txt";
File file = new File(fileName);
FileReader fr = new FileReader(file);
try (BufferedReader br = new BufferedReader(fr)) {
    String line;
    long scores = 0 ;
    while((line = br.readLine()) != null){
        int []t = conv(line.charAt(0), line.charAt(2));
        
        if (t[0] == t[1]){
            scores+= 3 + t[1];
        }
        else if (t[0] > t[1]){
            scores+=t[1];
        }
        else if (t[0] < t[1]){
            scores+= 6 + t[1];
        }
        System.out.println(t[0] + " - " + t[1]);
    
    }
    System.out.println(scores);
}
    }
}
