/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j8;

import java.io.IOException;

public class App {
    

    public static void main(String[] args) throws IOException {
        J8 j8 = new J8();
        System.out.println(j8.p1(j8.lecture("src/main/resources/j8.txt")));
    }
}
