/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j9;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    J9 j9 = new J9();
    @Test void p1() {
      
    }
}
