/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j4;

import java.io.IOException;


public class App {
  static J4 j4 = new J4();
    
    public static void main(String[] args) throws IOException {
        System.out.println(j4.j4P2("src/main/resources/j4.txt"));
    }
}
