/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package j5;

import java.io.IOException;

public class App {
  

    public static void main(String[] args) throws IOException {
        J5 j5 = new J5();
        j5.j5P1("src/main/resources/instructions.txt");
    }
}
